# main.yml
name: autobuild

on:
  pull_request:
    types:
      - closed
    branches:
      - 'master'

jobs:
 if_merged:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: "16.x"
      - name: Install dependencies
        run: npm install
      - run: npm run build --if-present
      #- run: npm test
